version: "3"

networks:
  gitea:
    external: false

volumes:
  wutty_etc:
    external: false
  wutty_home:
    external: false
  gitea_data:
    external: false
  db_data:
    external: false

services:
  server:
    image: my_gitea:0.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_DOMAIN=gitea
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__repository__DISABLE_HTTP_GIT=true
      - GITEA__server__SSH_DOMAIN=gitea
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=false
    restart: always
    networks:
      - gitea
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres_initdb:/docker-entrypoint-initdb.d:ro
  wutty:
    image: wutty:1.0
    restart: always
    environment:
      - GITEA_TOKEN=1424ae15be3bc8b0dd3f05b8fe6f04551736d4d3
    ports:
      - "5000:5000"
      - "1000:3000"
    networks:
      - gitea
    volumes:
      - wutty_etc:/etc
      - wutty_home:/home
  frontend:
    image: frontend:0.1
    restart: always
    ports:
      - "80:80"
    networks:
      - gitea

